name: Count Print Statements

on:
  push:

jobs:
  count-prints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install OpenAI Package
        run: pip install openai 

      - name: Run Python script
        run: python .github/scripts/script.py
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}